name: DrakesTab
version: 1.0
main: me.jackstar.drakestab.DrakesTabPlugin
api-version: '1.20'
authors: [JackStar]
description: Tablist and scoreboard for DrakesCraft
softdepend: [PlaceholderAPI, Vault, DrakesRanks]
commands:
  drakestab:
    description: Manage DrakesTab runtime
    usage: /drakestab <reload|status>
    permission: drakestab.admin
    aliases: [dtab, drtab]
permissions:
  drakestab.admin:
    description: Allows administration of DrakesTab
    default: op
